name: Generate ts-and-mongo Dev Container Image
on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - 'main'
    paths:
      - 'ts-and-mongo/**/*'
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  PACKAGE_DIR: ts-and-mongo
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository,, }}
  

jobs:
  devcontainer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install devcontainer cli
        run: npm install -g "@vscode/dev-container-cli"
      - name: Build devcontainer
        run: devcontainer build --no-cache --image-name ${{ env.IMAGE_NAME }} ${{ env.PACKAGE_DIR }}
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
      - name: Lowercase image name
        run: echo 
      - name: Publish
        run: docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.PACKAGE_DIR }}:latest"
